JellyfishSDK/whale

- __e2e__/module.testing.ts
- __sanity__/docker-compose.yml
- package-lock.json
- src/app.configuration.ts
- src/app.module.ts
- src/module.database/database.ts
- src/module.database/index.spec.ts
- src/module.database/index.ts
- src/module.database/provider.memory/index.ts
- src/module.database/provider.memory/memory.database.ts
/kind feature
This adds a provider agnostic database module that can be configured in `app.configuration.ts`
It allows configuration of database provider via env with `WHALE_DATABASE_PROVIDER: memory`.
An `Database` instance is provided at runtime by nestjs FactoryProvider.
https://github.com/DeFiCh/whale/blob/e507b2ecd1e4910a2a2946fc1d4a84b96f33d419/src/module.database/index.ts#L14-L26
The provider agnostic database modules is provided and registered at runtime but won't be initialized unless called upon.
https://github.com/DeFiCh/whale/blob/e507b2ecd1e4910a2a2946fc1d4a84b96f33d419/src/module.database/provider.memory/index.ts#L7-L13
> added provider agnostic database module

- jest.config.js
- src/app.configuration.ts
- src/app.module.ts
- tsconfig.json
/kind refactor
Currently, config uses default export which is frowned upon on ES modules. Switched to use named module export. 
Also in this PR; 
1. fixed jest.config path picking up wrong tests
2. enabled esModuleInterop to use cjs packages
> refactor config to use module export

- .github/workflows/defichain-dependencies.yml
/kind chore
Minor rename since we are updating defichain dependencies across the board, not just jellyfish.
> rename jellyfish-dependencies to defichain-dependencies

- __e2e__/call.e2e.ts
- __sanity__/postman_collection.json
- packages/whale-api-client/__tests__/api/call.test.ts
- packages/whale-api-client/__tests__/stub.client.ts
- packages/whale-api-client/src/api/call.ts
- packages/whale-api-client/src/api/rpc.ts
- packages/whale-api-client/src/api/transactions.ts
- packages/whale-api-client/src/errors/index.ts
- packages/whale-api-client/src/index.ts
- packages/whale-api-client/src/whale.api.client.ts
- packages/whale-api-client/src/whale.api.response.ts
- packages/whale-api-client/src/whale.rpc.client.ts
- src/module.api/_module.ts
- src/module.api/rpc.controller.spec.ts
- src/module.api/rpc.controller.ts
/kind feature
This implements the final and last piece of specification, the 'query chaining pagination' specification. Together with https://github.com/DeFiCh/whale/pull/35 where we implement an LSM based slice querying pagination specification. This implements the interfacing layer for querying data in that design.
`ApiResponsePagination` class facilitate the ability to pagination query chaining. It extends the `Array` class that can be accessed like an array, `res[0]`, `res.length`. After accessing all the items in the Array, you can use the same `ApiResponsePagination` to query the next set of items. Hence allowing you query pagination chaining until you exhaust all items in the list.
This capability boils down to 
1. A unique endpoint that defines a uniquely sorted list (aka LSM …
> whale-api-client: query pagination chaining

- packages/whale-api-client/src/whale.api.client.ts
- src/module.api/guards/network.guard.ts
/kind fix
Network playground is not available in `defich/ain`, hence it should not be in whale either. When testing light wallet, I tried to use the 'playground' network to parse address to get balance but it wasn't supported as it's not a real network type.
> 'playground' keyword should not be part of whale distribution

- .gitignore
- src/app.configuration.ts
- src/module.database/provider.level/module.ts
/kind fix
```diff
-  'production '
+  'production'
```
Due to this, I moved `isProd` into the config service
By default in production and mainnet, it will default to `.leveldb/mainnet` if not provided with a level location.
> fix typo in `LEVEL_UP_LOCATION`

- src/module.indexer/indexer.ts
- src/module.indexer/model/_main.ts
/kind fix
When RawBlock isn't indexed before invalidating kicks in, it will get stuck in invalidate loop. This fixes it.
> fix invalidate loop unable to fix raw block

- packages/whale-api-client/__tests__/whale.api.response.test.ts
- packages/whale-api-client/src/whale.api.response.ts
/kind fix
Built-in methods such as map, the filter creates a new array for functional programming. It does that with the constructor found in the static `Symbol.species` class property. This needs to be overridden as `ApiPagedResponse` constructor has a different signature.
> fix ArrayConstructor for functional chaining

- packages/whale-api-client/src/errors/api.error.ts
/kind fix
removed illegal `import { HttpStatus } from '@nestjs/common'` in packages
> removed illegal `import { HttpStatus } from '@nestjs/common'` in packages

- Dockerfile
/kind chore
Add curl to allow internal DOCKER HEALTHCHECK, https://docs.docker.com/engine/reference/builder/#healthcheck
Not configured within Dockerfile, should only be configured externally if required.
> add curl for docker healthcheck capability

- .github/workflows/ci.yml
- __sanity__/postman_collection.json
- src/module.api/_module.ts
- src/module.api/actuator.controller.ts
- src/module.api/actuator.e2e.ts
/kind feature
Rename `/_health/*` to`/ _actuator/*` to allow more features to be added for service controllability.
> rename _health to _actuator to allow more features to be added for service controllability

- src/module.defid/defid.probes.ts
/kind fix
- `defid` or `bitcoind` does not provide the ability to set a minimum number of peers to keep alive. 
- Having min peer of 5 (or any threshold) is still dangerous during a network cascade event as it will kill off basically all services when it dip below that threshold.
> updated defid probes to 'not connected to any peer'

- packages/whale-api-wallet/src/wallet.ts
/kind feature
Added withTransactionBuilder for WhaleWalletAccount to use Whale fee rate and prevout provider. This makes it easier to use craft a transaction with `whale-api-wallet`.
> added withTransactionBuilder for WhaleWalletAccount to use Whale feeRate and prevout provider

- .github/CODEOWNERS
- .idea/whale.iml
- package-lock.json
- package.json
- packages/whale-api-client/package.json
- packages/whale-api-wallet/package.json
- packages/whale-api-wallet/src/wallet.ts
/kind dependencies
1. `WalletEllipticPair` should be used now as `WalletHdNode` is not required for non-hd wallets.
2. included library consumer into whale packages CODEOWNERS
> Bump jellyfish deps to v0.24.0 with `WalletEllipticPair` update

- packages/whale-api-client/__tests__/api/transaction.test.ts
- packages/whale-api-client/src/api/transactions.ts
- src/module.api/transaction.controller.e2e.ts
- src/module.api/transaction.controller.spec.ts
- src/module.api/transaction.controller.ts
/kind feature
Endpoint to get a single transaction. 
Fixes #243
> Add `v0/:network/transactions/:id` endpoint

- packages/whale-api-client/__tests__/api/address.test.ts
- packages/whale-api-client/__tests__/api/blocks.test.ts
- packages/whale-api-client/__tests__/api/transaction.test.ts
- packages/whale-api-client/src/api/address.ts
- packages/whale-api-client/src/api/transactions.ts
- src/module.api/address.controller.e2e.ts
- src/module.api/transaction.controller.e2e.ts
- src/module.indexer/model/script.activity.ts
- src/module.indexer/model/script.aggregation.ts
- src/module.indexer/model/script.unspent.ts
- src/module.indexer/model/transaction.ts
- src/module.model/script.activity.spec.ts
- src/module.model/script.activity.ts
- src/module.model/script.aggregation.ts
- src/module.model/script.unspent.ts
- src/module.model/transaction.ts
/kind feature
Add `time` and `medianTime` to all indexed models with `block: {}`.
Fixes #175 
Fixes #178
> Included `time` and `medianTime` to endpoints: `address/*` & `blocks/transaction`

- package-lock.json
- package.json
- src/module.api/_module.ts
- src/module.api/cache/global.cache.ts
- src/module.api/cache/semaphore.cache.spec.ts
- src/module.api/cache/semaphore.cache.ts
/kind chore
Certain operations such as #136 and #246 are expensive to compute, this will limit the concurrency of that critical zone to just 2 with double-checked locking.
This is a pre-req for #246.
> Added SemaphoreCache to limit concurrency for certain expensive operations

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- src/module.api/poolpair.controller.e2e.ts
- src/module.api/poolpair.controller.spec.ts
- src/module.api/poolpair.controller.ts
- src/module.api/poolpair.service.ts
/kind refactor
`@Interval(60000)` is not consistent leading to `undefined` if not loaded when Whale instance mark as healthy. Refactored TVL calculations to use `SemaphoreCache` for better reliability where calculation will be computed via typical cache hit/miss.
> Refactor `TVL` calculation to use `SemaphoreCache`

- packages/whale-api-client/__tests__/api/stats.test.ts
- packages/whale-api-client/src/api/stats.ts
- packages/whale-api-client/src/index.ts
- packages/whale-api-client/src/whale.api.client.ts
- src/module.api/_module.ts
- src/module.api/poolpair.service.ts
- src/module.api/stats.controller.ts
/kind feature
A single endpoint to get statistical data of the current chain. Data are cached at a different time intervals, only `count.blocks` won't be cached.
```ts
export interface StatsData {
count: {
blocks: number
tokens: number
prices: number
}
tvl: {
total: number
dex: number
}
burned: {
total: number
fee: number
emission: number
address: number
}
price: {
usdt: number
}
}
```
Fixes #246
> Add `/stats` endpoint

- packages/whale-api-client/src/whale.api.response.ts
/kind fix
fixed ApiPagedResponse.nextToken to just return `string | undefined` since number is not allowed anymore
> fixed ApiPagedResponse.nextToken to just return `string | undefined`

- packages/whale-api-client/__tests__/api/prices.test.ts
- packages/whale-api-client/src/api/prices.ts
- src/module.api/price.controller.ts
/kind feature
Allow `feed?: OraclePriceFeed` in PriceOracle since it's always required for displaying at front end.
> added `feed?: OraclePriceFeed` in PriceOracle

- src/module.api/actuator.e2e.ts
- src/module.defid/defid.probes.ts
- src/module.model/_model.probes.ts
/kind fix
Reconfigure probes for dead if defid blocks are more than 4 headers behind.
`defid.readiness` dead if defid blocks are more than 4 headers behind
`model.readiness` dead synced blocks are more than 4 blocks behind
Also added probes healthy with peers testing with the new MasternodeGroup setup.
> reconfigure probes to unhealthy if defid blocks are more than 4 headers behind

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- packages/whale-api-client/src/api/poolpairs.ts
- src/module.api/poolpair.controller.e2e.ts
- src/module.api/poolpair.controller.spec.ts
- src/module.api/poolpair.controller.ts
/kind feature
Instead of having to `split('-')` the pool pair data symbol, this PR will include it within `a` and `b`.
> added a/b symbol for PoolPairData

- packages/whale-api-client/src/api/address.ts
- packages/whale-api-client/src/api/blocks.ts
- packages/whale-api-client/src/api/tokens.ts
- packages/whale-api-client/src/whale.api.client.ts
- src/app.configuration.ts
- src/app.module.ts
- src/version.e2e.ts
/kind feature
Allow endpoint prefix version to be overridden in production. 
> Instead of having a heavy infrastructure design with complex routing, this removes infra overhead and allows you to choose which is the main deployment by set `v0`.
> prefix version can now be overridden in production

- packages/whale-api-client/src/whale.api.client.ts
/kind fix
Override the options WhaleApiClient creates the side effect of permanently overriding it.
> fix WhaleApiClient options to create a new options instead of assigning

- .github/CODEOWNERS
- .github/workflows/ci/docker-compose.yml
- src/module.api/interceptors/exception.interceptor.ts
fixed ExceptionInterceptor to log the original error
/kind fix
- prevent certain 503 errors on the playground when testing.
- fixed `ExceptionInterceptor` to log the original error instead of transformed error
> added -rpcworkqueue=512 to docker-compose.yml

- src/module.indexer/model/block.minted.e2e.ts
- src/module.indexer/model/block.minted.ts
- src/module.indexer/rpc.block.provider.spec.ts
- src/module.indexer/rpc.block.provider.ts
/kind fix
This fixes an issue in the block minted mapper that causes the following error print out and causes the `indexGenesis` function to exit early:
```
[Nest] 10720  - 31/08/2021, 8:00:46 pm   ERROR [RPCBlockProvider] failed exceptionally
[Nest] 10720  - 31/08/2021, 8:00:46 pm   ERROR [RPCBlockProvider] ReadError: key cannot be `null` or `undefined`
```
Fixes #
> Fix block minted issue

- packages/whale-api-client/__tests__/api/blocks.test.ts
- packages/whale-api-client/__tests__/api/transaction.test.ts
- packages/whale-api-client/src/api/blocks.ts
- packages/whale-api-client/src/api/transactions.ts
- src/module.api/block.controller.e2e.ts
- src/module.api/block.controller.ts
- src/module.api/transaction.controller.e2e.ts
- src/module.api/transaction.controller.ts
- src/module.indexer/model/block.ts
- src/module.indexer/model/transaction.ts
- src/module.model/block.spec.ts
- src/module.model/block.ts
- src/module.model/transaction.ts
/kind fix
1. `blocks/:id/transactions` is not ordered by the first appearance in the block, currently it's sorted via txid. We need it to be sorted by the first appearance.
2. `/blocks` API `Block` model should include block reward, by checking the first transaction vout in the block.
3. `/transactions` API `Transaction` model should include total UTXO value out, the summing of all `vout` value.
See #383 https://github.com/DeFiCh/whale/issues/383
Fixes #383
> `/blocks` & `/transactions` improvement

- package-lock.json
- packages/whale-api-client/src/api/transactions.ts
- src/module.indexer/model/transaction.vin.ts
- src/module.model/transaction.vin.ts
/kind feature
Within TransactionVin, added `vout.script.hex` which was missing. This is required to know the previous script that chains to the next vout. No additional test was added because the body of vin wasn't tested (not critical component). 😰 
This is requested by @joeldavidw
> add `vout.script.hex` for `transaction.vin.ts`

- .idea/dictionaries/fuxing.xml
- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- packages/whale-api-client/__tests__/api/stats.test.ts
- packages/whale-api-client/src/api/stats.ts
- src/module.api/poolpair.controller.e2e.ts
- src/module.api/poolpair.service.ts
- src/module.api/stats.controller.ts
/kind fix
- USDT, USDC, DUSD pairs TVL will be calculated with itself now.
- USDT, USDC will be used collectively for USD of DFI calculation instead of just using USDT.
> fix USD TVL calculation by making it more flexible for FC update

- packages/whale-api-client/__tests__/api/address.vault.test.ts
- packages/whale-api-client/__tests__/api/loan.vault.test.ts
- packages/whale-api-client/src/api/loan.ts
- src/module.api/cache/defid.cache.ts
- src/module.api/cache/global.cache.ts
- src/module.api/loan.vault.controller.e2e.ts
- src/module.api/loan.vault.service.ts
/kind feature
Within LoanVault, loanSchemeId is denormalized to be `loanScheme: {...}` giving you richer information without having to call the API to get them. This is a breaking change.
> denormalize loan scheme data

- .github/dependabot.yml
/kind dependencies
With peer dependencies enabled, we can test how dependabot will auto-update all `@defichain` dependencies together.
> `dependabot.yml` allowed defichain deps to be auto updated

- packages/whale-api-client/__tests__/api/blocks.test.ts
- src/module.api/_core/api.query.ts
- src/module.api/loan.vault.service.ts
/kind chore
- size is checked to make sure it's not 0 due to upstream no checking
- /loans/vaults and /address/vaults allow size to 30 from 10 due changed on core side
> size refactor on core and vaults

- package.json
- packages/whale-api-client/__tests__/api/loan.collateral.test.ts
- packages/whale-api-client/__tests__/api/loan.token.test.ts
- packages/whale-api-client/__tests__/api/prices.test.ts
- packages/whale-api-client/src/api/loan.ts
- src/module.api/loan.collateral.controller.e2e.ts
- src/module.api/loan.controller.ts
- src/module.api/loan.token.controller.e2e.ts
/kind feature
Instead of getting the active price individually with `/prices` endpoint, this PR included the ActivePrice for all `LoanToken` and `LoanCollateral` operations.
> `ActivePrice` is fetched from Whale indexed database, this index is different from DeFiCh/ain, it index on its own spin loop cycle. `ActivePrice` can be undefined.
> include activePrice in /loans/tokens and /loans/collaterals

- packages/whale-api-client/__tests__/api/loan.vault.test.ts
- packages/whale-api-client/__tests__/api/prices.test.ts
- packages/whale-api-client/src/api/loan.ts
- src/module.api/loan.vault.service.ts
/kind feature
Instead of getting the active price individually with `/prices` endpoint, this PR included the ActivePrice for all `VaultLoanTokenAmount` in `Vault`. This doesn't perform arithmetic on the amount to get the USD value, you need to perform this on your own at the client side.
> `ActivePrice` is fetched from Whale indexed database, this index is different from DeFiCh/ain, it index on its own spin loop cycle. `ActivePrice` can be undefined.
> add ActivePrice to LoanTokenAmount for convenience

- package-lock.json
- packages/whale-api-client/package.json
- packages/whale-api-wallet/package.json
/kind dependencies
Also, removed peer for the lib package as it's enforced by jellyfish packages.
> bump jellyfish deps to 2.6.0 globally

- src/module.defid/defid.probes.ts
/kind fix
To check if still syncing with `idb` instead of `headers` as headers can be ahead even if the blocks are invalid.
> update defid.probes.ts to use initialblockdownload 

- packages/whale-api-client/package.json
- packages/whale-api-client/prebuild
/kind fix
Moved prebuild script `version.ts` (sets the versions for client) into an executable script due to `package.json` parsing error in `defichain-dependencies.yml`
> moved prebuild into a script due to package.json parsing error in workflow

- packages/whale-api-client/__tests__/api/loan.auction.test.ts
- packages/whale-api-client/src/api/loan.ts
- src/module.api/loan.auction.controller.e2e.ts
- src/module.api/loan.vault.service.ts
/kind fix
New highestBid object is added to listVaults, getVault and listAuctions RPCs. 
Fixes #
> Add highestBid returned object to vault and auction endpoints

- packages/whale-api-client/__tests__/api/rawtx.test.ts
- src/module.api/rawtx.controller.ts
/kind fix
Remove lower limit and set to a default of 0.1 DFI for `/rawtx/send` and `/rawtx/test` operations due to increased transaction defichain is handling.
> set /rawtx/send defaultMaxFeeRate to 0.1

- src/module.model/_model.probes.ts
> chore(health): allow model readiness synced blocks to be up to 10 blocks behind

- packages/whale-api-wallet/src/wallet.ts
/kind chore
Increase prevout size from 50 to 200 for WhaleWalletAccount PrevoutProvider. This allows more prevout to be collected for Whale Wallet Transaction creation.
> chore(whale-api-client): increase prevout size to 200 for WhaleWalletAccount

- src/module.model/_model.probes.ts
/kind chore
A window of 10 is too wide, changing to back to 4. If any health check configuration is to be done; it should be done on the server side,
> chore(model.probes.ts): change model readiness window to 4

- src/module.database/provider.level/level.database.ts
/kind chore
LevelDB was created long ago in the era of rotating disks. While level has RocksDB is a drop-in replacement for LevelDB, it's not as widely used (https://www.npmjs.com/package/rocksdb vs https://www.npmjs.com/package/level).
This PR attempts to tune the SSTable settings by allowing more files to be opened and increasing the size of each file that will benefit modern systems.
Related to https://github.com/DeFiCh/jellyfish/issues/979
> chore(database): increase max open file and max file size to benefit modern system

- src/e2e.module.ts
- src/module.indexer/rpc.block.provider.ts
/kind chore
After `const indexed = await this.blockMapper.getHighest()`
Previously 4 RPC to check if there is a new block:
1. `isBestChain()` -> `this.client.blockchain.getBlockHash(indexed.height)`
2. `const highest = await this.client.blockchain.getBlockCount()` for `if (indexed.height + 1 > highest)` for has next block
3. `const nextHash = await this.client.blockchain.getBlockHash(nextHeight)`
4. `const block = await this.client.blockchain.getBlock(hash, 2)`
This new implementation optimizes the RPCBlockProvider to just use 2 RPC call with the same result:
1. `const nextHash = await this.client.blockchain.getBlockHash(indexed.height + 1)`
- returns if not found = no next block
2. `const nextBlock = await this.client.blockchain.getBlock(nextHash, 2)` 
- Also compare isBestChain via …
> chore(indexer): reduce the amount of RPC call from 4 to 2 for indexing

- src/module.model/_model.probes.ts
/kind chore
Lower and move service reliability granularity to orchestrator services.
> chore(health-check): readiness synced blocks are more than 2 blocks behind

- .idea/dictionaries/fuxing.xml
- package-lock.json
- packages/tsconfig.json
- packages/whale-api-client/__tests__/stub.client.ts
- packages/whale-api-client/__tests__/whale.rpc.client.test.ts
- packages/whale-api-client/package.json
- packages/whale-api-client/src/api/rpc.ts
- packages/whale-api-client/src/whale.rpc.client.ts
- src/module.api/_core/api.paged.response.ts
- src/module.api/_core/api.response.ts
- src/module.api/interceptors/response.interceptor.ts
- src/module.api/rpc.controller.spec.ts
- src/module.api/rpc.controller.ts
/kind feature
Expose whitelisted JSON RPC 1.0 directly via RpcController so that `@defichain/jellyfish-api-jsonrpc` can use Ocean infrastructure directly.
> feature(json-rpc): expose whitelisted defid JSON RPC 1.0

- .idea/dictionaries/fuxing.xml
- jest.config.js
/kind chore
For PoolSwap Aggregation tests, they are much more complex hence the increased duration. Separating the change into this PR.
> chore(core): testTimeout increase to 300000 for longer more complex tests

- src/module.indexer/model/dftx/pool.swap.aggregated.ts
/kind chore
Bucket indexer performance optimization.
> chore(indexer): reverse bucket loop order, to exit when an index when interval already exist

- .idea/dictionaries/fuxing.xml
- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- packages/whale-api-client/src/api/poolpairs.ts
- src/module.api/poolpair.controller.ts
- src/module.api/poolpair.service.ts
/kind chore
Included PoolSwap from/to fields for convenience in swap history.
```ts
export interface PoolSwapData {
/**
* To handle for optional value as Whale service might fail to resolve when indexing
*/
from?: PoolSwapFromToData
/**
* To handle for optional value as Whale service might fail to resolve when indexing
*/
to?: PoolSwapFromToData
}
export interface PoolSwapFromToData {
address: string
amount: string
symbol: string
}
```
```ts
/**
* List pool swaps with from/to
*
* @param {string} id poolpair id
* @param {number} [size=10] of PoolSwap to query, max of 20 per page
* @param {string} next set of PoolSwap
* @return {Promise<ApiPagedResponse<PoolSwapData>>}
*/
async listPoolSwapsVerbose (id: string, size: number = 10, next?: string): Promise<ApiPagedResponse<PoolSwapData>> { …
```
> feature(controller): Resolve PoolSwap from/to from `AccountHistory`

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- src/module.api/poolpair.service.ts
/kind chore
- This PR allows `to` to be optional when history cannot be resolved.
- Also add a `CompositeSwap` transaction to `poolpairs.test.ts` so that all the correct scenarios are tested.
> chore(poolpair.controller): allow `to` to be optional when history cannot be resolved

- package-lock.json
- package.json
- packages/whale-api-client/src/api/poolpairs.ts
- src/module.api/poolpair.controller.e2e.ts
- src/module.api/poolpair.controller.ts
- src/module.api/poolpair.service.ts
/kind feature
- Implements `/poolpairs/paths/swappable/1` endpoint to retrieve all swappable tokens given a token
- To merge after #822 
Returns response:
`poolswap/paths/swappable/1`
```javascript
{
fromToken: { id: '1', symbol: 'A' },
swappableTokens: [
{ id: '7', symbol: 'G' },
{ id: '0', symbol: 'DFI' },
{ id: '24', symbol: 'USDT' },
{ id: '6', symbol: 'F' },
{ id: '5', symbol: 'E' },
{ id: '4', symbol: 'D' },
{ id: '3', symbol: 'C' },
{ id: '2', symbol: 'B' }
]
}
```
Fixes part of #809
> feat(controller): token swap pathfinding getallswappabletokens

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- packages/whale-api-client/src/api/poolpairs.ts
- src/module.api/pipes/api.validation.pipe.ts
- src/module.api/poolpair.controller.ts
/kind feature
Exposes functionality via whale-api-client that was added in:
- #822 
- #849
Fixes part of https://github.com/DeFiCh/whale/issues/809
- changed ParseIntPipe to StringIsInteger validation pipe so a String value is passed to the controller instead of a Number (all places using ParseIntPipe but expecting a string are lulled into a false sense of security)
> feat(swap-pathfinding): glue api client with swap path finding endpoints

- packages/whale-api-client/__tests__/api/prices.test.ts
- packages/whale-api-client/src/api/prices.ts
- src/module.api/price.controller.ts
/kind feature
```ts
/**
* Aggregated interval time range in seconds.
* - Interval that aggregated in seconds
* - Start Time Inclusive
* - End Time Exclusive
*/
time: {
interval: number
start: number
end: number
}
```
> feat(prices): include aggregated time range in Indexed PriceData

- src/module.api/poolpair.controller.e2e.ts
- src/module.api/poolpair.prices.service.ts
/kind fix
- Fixes the issue of `/dexprices?denomination=SYMBOL` ignoring SYMBOL and returning wrong result
- Issue was that the denomination symbol wasn't being added to `listDexPrices` cache key, so all queries were hitting 'LIST_DEX_PRICES' regardless of the denomination symbol
> fix(poolpair/dexprices): add denomination symbol to dexprices cache key

- src/module.api/cache/defid.cache.spec.ts
- src/module.api/cache/defid.cache.ts
- src/module.api/cache/global.cache.ts
- src/module.api/poolswap.pathfinding.service.ts
/kind fix
- Fixes price updates taking too long due to reliance on 10m TTL caching for poolpairinfo
- Pagination needs to be followed in order to retrieve the full list - this is made explicit with a `while (true)`
> fix(poolpair/paths): make defidcache.getpoolpairinfo rely on 1m cached list instead of 10m cache

- src/module.api/poolpair.controller.e2e.ts
- src/module.api/poolswap.pathfinding.service.ts
/kind fix
- Change /poolpairs/paths/best/from/1/to/0 to return direct path if a direct poolpair is available
> fix(poolpair/pathfinding): always use direct path if available

- src/module.api/stats.controller.ts
Optimize expensive stats.controller.ts calls by using common cache getburninfo and getloaninfo for operations.
> chore(stats): optimize stats.controller.ts by using common cache getburninfo

- src/module.api/cache/semaphore.cache.spec.ts
- src/module.api/cache/semaphore.cache.ts
Due to higher than normal back pressure on defid, this PR reduces semaphore cache concurrency to 1 to reduce upstream back pressure.
> chore(cache): reduce semaphore cache concurrency to reduce locking

- Dockerfile
On high trafficked whale instances the node heap limit of `2 gb` isn't enough.
> chore(memory): increase node heap size to 4gb

- packages/whale-api-client/__tests__/stub.client.ts
- packages/whale-api-client/package.json
- packages/whale-api-client/prebuild
- packages/whale-api-client/src/version.ts
- packages/whale-api-client/src/whale.api.client.ts
Currently WhaleApiClient options version default to the current npm release version. I think to ensure forever backward compatibility for users, we should default to v0.
Fixes https://github.com/JellyfishSDK/whale/issues/979
> chore(whale-api-client): Default whale api client to v0 and let url be optional
