JellyfishSDK/whale

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/release-publish.yml
- Dockerfile
- __e2e__/call.e2e.ts
- docker-compose.yml
- package-lock.json
- package.json
- src/module-api/commons/guard.network.ts
- src/module-api/controller.call.ts
/kind chore
Setup docker workflow to build at merge and publish at release.
Targetted platforms are `linux/amd64` and `linux/arm64`.
Also renamed `v1.0` to `v1` for brevity as there should not be any breaking change for v1.0 to v1.1
> setup docker workflows

- .github/governance.yml
- .github/labeler.yml
- .github/labels.yml
- .github/workflows/ci.yml
- .idea/dictionaries/fuxing.xml
- __e2e__/README.md
- __e2e__/health.e2e.ts
- __sanity__/README.md
- __sanity__/docker-compose.yml
- __sanity__/postman_collection.json
- __sanity__/wait-for.sh
- src/app.module.ts
- src/module.api/call.controller.spec.ts
- src/module.api/call.controller.ts
- src/module.api/health.controller.ts
- src/module.api/index.ts
- src/module.defid/defid.indicator.ts
- src/module.defid/index.ts
- src/module.health/index.ts
- src/module.health/probe.indicator.ts
/kind feature
Added health module, this health module is used to provide health check with liveness and readiness probes. Created to carefully match Kubernetes deployment semantic. 
Also included `__sanity__` testing.
> added health module

- .idea/dictionaries/fuxing.xml
- README.md
- __sanity__/README.md
/kind docs
Updated docs to reflect what are the current DeFi Whale testing paradigm for open-source onboarding.
> updated docs for defi whale testing paradigm

- .codeclimate.yml
- .github/CODEOWNERS
- .github/labeler.yml
/kind chore
Include current code contributor to automatic code review assignment.
> updated codeowners to include current contributors

- .github/workflows/jellyfish-dependencies.yml
- package-lock.json
/kind dependencies
- updated jellyfish-dependencies
- also added a cron workflow to auto update deps every 2 hour
> updated jellyfish-dependencies

- .github/CODEOWNERS
- .github/governance.yml
- .github/labeler.yml
- .github/labels.yml
- .github/workflows/jellyfish-dependencies.yml
- .idea/dictionaries/fuxing.xml
- package-lock.json
- package.json
- src/module.database/database.spec/_model.ts
- src/module.database/model.ts
- src/module.database/provider.level/level.database.ts
/kind refactor
- refactor `src/module.database/_model` for better typescript support
- removed `@nestjs/cqrs`
- cleanup governance.yml
- fixed `.github/workflows/jellyfish-dependencies.yml`
- fixed `labeler.yml` being in the wrong directory
> refactor, fixes & code governance

- .github/workflows/ci.yml
- .github/workflows/jellyfish-dependencies.yml
- README.md
- src/app.module.ts
- src/module.model/_hex.encoder.spec.ts
- src/module.model/_hex.encoder.ts
- src/module.model/_module.ts
- src/module.model/block.spec.ts
- src/module.model/block.ts
- src/module.model/raw.block.spec.ts
- src/module.model/raw.block.ts
- src/module.model/script.activity.spec.ts
- src/module.model/script.activity.ts
- src/module.model/script.aggregation.ts
- src/module.model/script.unspent.ts
- src/module.model/transaction.ts
- src/module.model/transaction.vin.ts
- src/module.model/transaction.vout.ts
/kind feature
This adds all the models that need to be indexed in DeFi Whale. Not all mapper are tested for better velocity. They will be tested with the indexer
> new module.model for indexed data

- .github/workflows/jellyfish-dependencies.yml
- package-lock.json
- package.json
/kind chore
Release v0.0.24 and added @defichain/testing to dev deps
> added @defichain/testing to dev

- .github/workflows/ci.yml
/kind chore
parallelized docker buildx in `ci.yml` for faster workflow
> ci.yml to use matrix for faster build

- src/module.database/provider.level/level.database.spec.ts
> removed unused config from level-db test

- .github/workflows/ci.yml
/kind fix
Lint script is bugged, fixing it.
> fix lint not failing

- .github/workflows/oss-governance-project.yml
/kind chore
All non-forked pull request in this repo should be added to project board, this automates the process.
> oss-governance-project to auto update project board

- packages/whale-api-client/__tests__/api/poolpair.test.ts
- packages/whale-api-client/src/api/poolpair.ts
- packages/whale-api-client/src/index.ts
- packages/whale-api-client/src/whale.api.client.ts
- src/module.api/_module.ts
- src/module.api/cache/poolpair.info.cache.spec.ts
- src/module.api/cache/poolpair.info.cache.ts
- src/module.api/poolpair.controller.spec.ts
- src/module.api/poolpair.controller.ts
> added poolpairs.controller.ts

- .github/workflows/oss-governance-project.yml
> oss-governance-project update due to board changes

- .codeclimate.yml
- .github/workflows/defichain-dependencies.yml
- package-lock.json
- package.json
- packages/whale-api-client/__tests__/api/address.test.ts
- packages/whale-api-client/__tests__/stub.service.ts
- packages/whale-api-client/src/api/address.ts
- packages/whale-api-client/src/whale.api.response.ts
- src/e2e.module.ts
- src/module.api/address.controller.e2e.ts
- src/module.api/address.controller.spec.ts
- src/module.api/address.controller.ts
/kind feature
Implements 4 controller with `whale-api-client` e2e tested.
1. `GET: /address/:address/balance`
1. `GET: /address/:address/aggregation`
1. `GET: /address/:address/transactions`
1. `GET: /address/:address/transactions/unspent`
Created 2 issue https://github.com/DeFiCh/whale/issues/88  https://github.com/DeFiCh/whale/issues/89 to tackle bad design patterns created by this PR.
Fixes #5
> added address.controller.ts

- .github/workflows/defichain-dependencies.yml
- package-lock.json
- packages/whale-api-client/__tests__/api/poolpair.test.ts
- packages/whale-api-client/__tests__/api/transaction.test.ts
- packages/whale-api-client/src/api/transactions.ts
- src/module.api/health.e2e.ts
- src/module.api/transactions.controller.spec.ts
- src/module.api/transactions.controller.ts
- src/module.model/raw.block.spec.ts
/kind feature
Added `GET: transactions/estimate-fee` for WhaleFeeRateProvider.
Also fixed flaky tests and refactor things that are not required.
> added transactions/estimate-fee endpoint

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/defichain-dependencies.yml
- .github/workflows/oss-governance-bot.yml
- .github/workflows/oss-governance-labeler.yml
- .github/workflows/oss-governance-project.yml
- .github/workflows/release-publish.yml
- .github/workflows/sync-labels.yml
/kind chore
- Fixed all workflow actions version to a commit SHA.
- Added self-assign workflow
> updated & cleanup `.github/workflows`

- .github/dependabot.yml
- __sanity__/docker-compose.yml
- packages/whale-api-client/src/index.ts
/kind refactor
1. fix export typo - rename `call` to `rpc`
2. update ain from 1.6.3 to 1.6.4
3. dependabot to ignore `@defichain/*`
> refactor type & deps update

- src/module.api/health.controller.ts
- src/module.defid/_module.ts
- src/module.defid/defid.indicator.ts
> rename inconsistent *HealthIndicator to *ProbeIndicator

- package.json
- packages/whale-api-client/src/whale.api.client.ts
- src/module.api/guards/network.guard.ts
/kind feature
Playground is a special network for testing, see https://github.com/DeFiCh/playground
> added new network playground

- .github/workflows/release-publish.yml
- src/main.ts
/kind chore
- Enabled COR by default
- Fixed publish script version not allowing double-digit version
> enabled cors and fix publish script

- src/main.ts
- src/module.database/provider.level/module.ts
/kind chore
- level db provider to use a fixed database location in production
- fixed cors settings
> level db to use a fixed database in production

- packages/whale-api-client/src/whale.api.client.ts
> removed invalid 'url' import

- .github/CODEOWNERS
- .github/workflows/oss-governance-project-pr.yml
- .idea/dictionaries/fuxing.xml
/kind chore
Updated CODEOWNERS to include @canonbrother in project health, @ivan-zynesis in api-wallet.
Also fixed `oss-governance-project-pr.yml`.
> updated CODEOWNERS

- src/module.indexer/indexer.ts
/kind fix
fix fetch block before updating status or it will get stuck in invalidating loop.
> fix invalidating loop with fetch block before updating status

- package-lock.json
- packages/whale-api-client/package.json
- packages/whale-api-client/src/whale.api.client.ts
/kind fix
Added polyfill for URLSearchParams
Fixes #
> added polyfill for URLSearchParams

- packages/whale-api-client/src/whale.api.client.ts
/kind fix
Added network type `playground` to prevent typing errors on Wallet
Fixes #
> add 'playground' network type

- .github/workflows/defichain-dependencies.yml
- package.json
> improved @defichain/* update workflow

- __sanity__/postman_collection.json
- packages/whale-api-client/__tests__/api/poolpair.test.ts
- packages/whale-api-client/__tests__/api/rpc.test.ts
- packages/whale-api-client/__tests__/api/tokens.test.ts
- packages/whale-api-client/__tests__/api/transaction.test.ts
- packages/whale-api-client/__tests__/stub.client.ts
- packages/whale-api-client/src/whale.api.client.ts
- src/module.api/_core/api.version.ts
- src/module.api/_module.ts
- src/module.api/address.controller.ts
- src/module.api/guards/network.guard.e2e.ts
- src/module.api/guards/network.guard.ts
- src/module.api/poolpair.controller.ts
- src/module.api/rpc.controller.ts
- src/module.api/token.controller.ts
- src/module.api/transaction.controller.ts
/kind feature
> Incompatible breaking change, hence a feature
To indicate this version is beta as we are still in **v0**.x.x phase of DeFi Whale.
> prefixed version path to v0 to indicate beta release

- src/main.ts
/kind feature
allow port to be override to allow flexible deployment
> allow port to be override to allow flexible deployment

- src/module.api/actuator.controller.ts
- src/module.api/actuator.e2e.ts
- src/module.defid/_module.ts
- src/module.defid/defid.probes.ts
- src/module.model/_model.probes.ts
- src/module.model/_module.ts
/kind chore
- renamed `defid.indicator` to `defid.probes` for a more fitting name.
- added `model.probes` to check the health of indexed data
- `defid.probes` is refactored to use more lightweight operations for liveness and <5 peers instead of !=0 peers
> added model probes indicator for actuator for healthcheck

- src/module.api/transaction.controller.spec.ts
- src/module.api/transaction.controller.ts
/kind feature
Added message for all errors
Fixes #198
> Transaction `test/send` to include all error message as BadRequest

- packages/whale-api-client/src/api/poolpair.ts
- packages/whale-api-client/src/api/tokens.ts
/kind fix
`next` param on certain controllers is wrong.
Fixes #220
> Fixed next param type in `token` and `poolpair` controllers

- packages/whale-api-client/__tests__/stub.service.ts
/kind refactor
To wait for indexer to reach a block height
See https://github.com/DeFiCh/whale/pull/191#discussion_r666094053
Fixes #
> Add waitForIndexedHeight function

- packages/whale-api-client/__tests__/api/tokens.test.ts
- packages/whale-api-client/src/api/tokens.ts
- src/module.api/token.controller.e2e.ts
- src/module.api/token.controller.spec.ts
- src/module.api/token.controller.ts
/kind fix
Removed undefined data from token controller 
Fixes #206
> Made collateral address optional if it is undefined. 

- packages/whale-api-client/__tests__/api/masternode.test.ts
- packages/whale-api-client/src/api/masternode.ts
- packages/whale-api-client/src/index.ts
- packages/whale-api-client/src/whale.api.client.ts
- src/module.api/_module.ts
- src/module.api/masternode.controller.e2e.ts
- src/module.api/masternode.controller.spec.ts
- src/module.api/masternode.controller.ts
- src/module.api/rpc.controller.spec.ts
> Masternode controller

- .github/workflows/defichain-dependencies.yml
- .github/workflows/nestjs-dependencies.yml
> Added @nestjs deps update workflow

- .github/workflows/defichain-dependencies.yml
> fix defichain-dependencies.yml not to update whale deps

- package-lock.json
- package.json
- packages/whale-api-client/__tests__/api/address.test.ts
- packages/whale-api-client/__tests__/api/transaction.test.ts
- packages/whale-api-client/package.json
- packages/whale-api-wallet/package.json
- src/module.api/actuator.e2e.ts
- src/module.api/transaction.controller.e2e.ts
- src/module.indexer/indexer.spec/_testing.module.ts
- src/module.indexer/indexer.spec/block.spec.ts
- src/module.indexer/indexer.spec/script.spec.ts
- src/module.indexer/indexer.spec/transaction.spec.ts
/kind chore
Fix tests after changes, mostly adding generate to various tests
Fixes #
> Fix dependency bump

- src/module.indexer/indexer.spec/_testing.module.ts
- src/module.indexer/indexer.spec/block.spec.ts
/kind chore
Add basic testing for block invalidation
Fixes #
> Add basic testing for block invalidation

- .github/workflows/ci/postman_collection.json
> fix ci.yml removed readiness check

- package.json
- packages/whale-api-client/package.json
- packages/whale-api-client/src/version.ts
> fix lerna with no-private scope

- .github/workflows/release-publish.yml
- package.json
- packages/whale-api-client/package.json
- packages/whale-api-client/src/version.ts
> fixed version:set to set before packages:build

- packages/whale-api-client/__tests__/api/blocks.test.ts
- packages/whale-api-client/src/api/blocks.ts
- packages/whale-api-client/src/api/transactions.ts
- src/module.api/block.controller.e2e.ts
- src/module.api/block.controller.ts
> /blocks/:id/transactions/:txid/vins & /blocks/:id/transactions/:txid/vouts endpoints

- .idea/dictionaries/fuxing.xml
- tsconfig.json
/kind chore
To use more up-to-date es2019 features.
> tsconfig.target to use `es2019`

- src/module.api/actuator.e2e.ts
- src/module.defid/defid.probes.ts
- src/module.model/_model.probes.ts
> /_actuator/probes to include details of alive probes

- packages/whale-api-client/src/whale.api.client.ts
> typescript template string is a relatively new feature, reverting to just stirng

- packages/whale-api-client/__tests__/api/blocks.test.ts
- src/module.api/_core/api.query.ts
> Add transform decorator to limit the size property of PaginationQuery to 60

- src/module.indexer/model/dftx.indexer.ts
> fixed getDfTxTransactions so that it only parse OP_DEFI_TX if present

- package-lock.json
> fixed `@defichain/whale-api-client` deps linking

- src/module.indexer/model/dftx/appointed.oracle.spec.ts
- src/module.indexer/model/dftx/remove.oracle.spec.ts
- src/module.indexer/model/dftx/set.oracle.data.spec.ts
- src/module.indexer/model/dftx/update.oracle.spec.ts
/kind feature
To ensure the result indexed by indexers accurate, we need to validate the values with values returned from Oracle rpcs like `getOracleData` and `listPrices`. 
Fixes #
> Add more test units to validate Oracle indexers result with Oracle rpcs result

- src/module.indexer/model/dftx.indexer.ts
/kind chore
Due to the sporadic nature of upgrading the blockchain, the DfTx schematic might change. This PR will prevent indexer stall by logging errors instead of erroring. 
> We can improve on this design by having a separated indexing pipeline. Where a failed pipeline won't affect another indexer pipeline.
> MainDfTxIndexer to log error instead of crashing to prevent indexer stall

- src/module.api/cache/defid.cache.spec.ts
- src/module.api/cache/defid.cache.ts
- src/module.api/cache/global.cache.ts
- src/module.api/cache/semaphore.cache.ts
- src/module.api/interceptors/exception.interceptor.ts
/kind refactor
- Added logging to ExceptionInterceptor
- Moved CachePrefix to global.cache.ts with the inclusion of `SEMAPHORE`
> added logging to ExceptionInterceptor

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- packages/whale-api-client/src/api/poolpairs.ts
- packages/whale-api-client/src/whale.api.response.ts
- src/module.api/poolpair.controller.e2e.ts
- src/module.api/poolpair.controller.spec.ts
- src/module.api/poolpair.controller.ts
- src/module.api/poolpair.service.ts
/kind feature
Add basic APR calculation to `poolpair-controller`
Fixes #307
> Add basic APR calculation to `poolpair-controller`

- packages/whale-api-client/__tests__/api/stats.test.ts
- packages/whale-api-client/src/api/stats.ts
- src/module.api/stats.controller.ts
- src/module.indexer/model/dftx/create.masternode.spec.ts
- src/module.indexer/model/dftx/create.masternode.ts
- src/module.indexer/model/dftx/resign.masternode.spec.ts
- src/module.indexer/model/dftx/resign.masternode.ts
- src/module.model/_module.ts
- src/module.model/masternode.stats.ts
- src/module.model/masternode.ts
/kind feature
This indexes masternode stats, closes https://github.com/DeFiCh/whale/issues/325
Fixes #
> `masternode.stats` Indexer

- packages/whale-api-client/src/api/address.ts
- src/module.api/address.controller.e2e.ts
- src/module.api/address.controller.spec.ts
- src/module.api/address.controller.ts
/kind feature
Added `displaySymbol` to address controller
Fixes #
> Added `displaySymbol` to address controller

- .github/workflows/oss-governance-project-pr.yml
> fix oss-governance-project-pr.yml

- packages/whale-api-client/__tests__/api/stats.test.ts
- packages/whale-api-client/src/api/stats.ts
- src/module.api/stats.controller.ts
/kind feature
Added block difficulty to stat endpoint 
Fixes #394
> Added block difficulty to stat endpoint

- packages/whale-api-client/__tests__/api/transaction.test.ts
- src/module.api/transaction.controller.e2e.ts
- src/module.api/transaction.controller.ts
- src/module.model/transaction.vout.ts
/kind fix
Fix for transaction pagination as the correct next transaction id was not provided
> Fixed transaction api pagination

- packages/whale-api-client/__tests__/errors/index.test.ts
- packages/whale-api-client/src/api/oracles.ts
- packages/whale-api-client/src/api/prices.ts
- packages/whale-api-client/src/api/rawtx.ts
- packages/whale-api-client/src/api/rpc.ts
- packages/whale-api-client/src/api/transactions.ts
- packages/whale-api-client/src/whale.api.client.ts
> Updated JSDoc and tests

- packages/whale-api-client/__tests__/api/masternodes.test.ts
- src/module.api/masternode.controller.e2e.ts
- src/module.database/provider.level/level.database.ts
/kind fix
Not implementing a real fix due to pending Migration/Consolidation to jellyfish.
> fixed flaky Masternode test due to race delete/write

- package-lock.json
- package.json
> revert level to 7.0.0 due to possible M1 regression

- .github/workflows/ci.yml
- .github/workflows/defichain-dependencies.yml
- .github/workflows/nestjs-dependencies.yml
- .github/workflows/release-publish.yml
- Dockerfile
- src/module.api/loan.controller.ts
> bump node to v16

- packages/whale-api-client/__tests__/api/prices.test.ts
- src/module.indexer/model/dftx/oracle.e2e.ts
/kind chore
Reinstate oracle price interval tests
Fixes #
> Reinstate oracle price interval tests

- src/module.indexer/model/dftx.indexer.ts
- src/module.indexer/model/dftx/create.poolpair.spec.ts
- src/module.indexer/model/dftx/create.token.spec.ts
- src/module.indexer/model/dftx/update.poolpair.spec.ts
/kind fix
v2.0.0 minor regression, we aren't using that index yet
> disabled CreateToken/CreatePoolPair/UpdatePoolPair operations

- packages/whale-api-client/__tests__/api/stats.test.ts
- packages/whale-api-client/src/api/stats.ts
- src/module.api/stats.controller.ts
/kind feature
Added net data to stats api endpoint
- protocolversion
- subversion
- version
Fixes #
> Add `net` data into `stats` endpoint

- src/module.api/address.controller.ts
- src/module.api/loan.vault.service.ts
- src/module.api/token.controller.ts
> refactor displaySymbol DUSD to be parsed the same as DFI as it's a native token

- src/module.api/poolpair.controller.ts
> fix display symbol for DUSD

- src/module.indexer/model/dftx/create.poolpair.ts
/kind feature
Change symbol trimming based on FC height
Fixes #567
> Change symbol trimming based on FC height

- .github/CODEOWNERS
> add CODEOWNERS for indexer and model

- src/module.indexer/model/dftx.indexer.ts
- src/module.indexer/model/dftx/_module.ts
- src/module.indexer/model/dftx/create.poolpair.spec.ts
- src/module.indexer/model/dftx/create.token.spec.ts
- src/module.indexer/model/dftx/set.loan.token.spec.ts
- src/module.indexer/model/dftx/set.loan.token.ts
- src/module.indexer/model/dftx/update.poolpair.spec.ts
/kind fix
Adds token creation indexing for set loan token
Fixes #
> Fix token mapping

- packages/whale-api-client/__tests__/api/oracles.test.ts
- src/module.indexer/model/dftx/appoint.oracle.ts
- src/module.indexer/model/dftx/appointed.oracle.spec.ts
- src/module.indexer/model/dftx/remove.oracle.spec.ts
- src/module.indexer/model/dftx/remove.oracle.ts
- src/module.indexer/model/dftx/update.oracle.spec.ts
- src/module.indexer/model/dftx/update.oracle.ts
- src/module.model/oracle.history.ts
- src/module.model/oracle.ts
/kind feature
Add owner address to `oracle-indexer`
Fixes #586
> Add owner address to `oracle-indexer`

- packages/whale-api-client/__tests__/api/masternodes.test.ts
- packages/whale-api-client/__tests__/api/prices.test.ts
- packages/whale-api-client/__tests__/stub.service.ts
- src/e2e.module.ts
- src/module.api/address.controller.e2e.ts
- src/module.api/masternode.controller.e2e.ts
- src/module.indexer/model/dftx/create.masternode.spec.ts
/kind fix
Due to the race condition of the database writing, adding a global delay to prevent flaky failure.
> add global delay for waitForIndexedHeight due to race condition

- .eslintrc
- .github/workflows/ci.yml
- .idea/codeStyles/Project.xml
- .idea/dictionaries/fuxing.xml
- package-lock.json
- package.json
- packages/whale-api-client/__tests__/errors/index.test.ts
- packages/whale-api-client/src/version.ts
- src/app.configuration.ts
- src/module.api/cache/defid.cache.ts
- src/module.api/cache/semaphore.cache.spec.ts
- src/module.api/masternode.controller.ts
- src/module.api/masternode.service.ts
- src/module.api/pipes/api.validation.pipe.ts
- src/module.api/stats.controller.ts
- src/module.database/_module.spec.ts
- src/module.indexer/model/dftx/create.masternode.ts
- src/module.indexer/model/dftx/create.poolpair.ts
- src/module.indexer/model/transaction.vin.ts
- src/module.model/script.activity.spec.ts
- src/module.model/token.ts
> removed ts-standard to use eslint directly

- packages/whale-api-client/__tests__/api/prices.test.ts
- src/module.indexer/model/dftx.indexer.ts
- src/module.indexer/model/dftx/_abstract.ts
- src/module.indexer/model/dftx/active.price.ts
- src/module.indexer/model/dftx/appoint.oracle.ts
- src/module.indexer/model/dftx/create.masternode.ts
- src/module.indexer/model/dftx/create.poolpair.ts
- src/module.indexer/model/dftx/create.token.ts
- src/module.indexer/model/dftx/remove.oracle.ts
- src/module.indexer/model/dftx/resign.masternode.ts
- src/module.indexer/model/dftx/set.loan.token.ts
- src/module.indexer/model/dftx/set.oracle.data.interval.ts
- src/module.indexer/model/dftx/set.oracle.data.ts
- src/module.indexer/model/dftx/update.oracle.ts
- src/module.indexer/model/dftx/update.poolpair.ts
/kind feature
This parses the block sequentially per transaction, allowing us to maintain parity with a regular node's blockchain indexing.
Fixes #
> Refactor `dftx.indexer`

- src/module.api/rawtx.controller.ts
> disable CCompositeSwap.OP_CODE on rawtx/send

- src/module.api/rawtx.controller.spec.ts
- src/module.api/rawtx.controller.ts
> add validation for send

- .github/workflows/defichain-dependencies.yml
/kind
fix defichain-dependencies.yml not updating all package.json
> fix defichain-dependencies.yml not updating all package.json

- src/module.api/_core/api.query.ts
- src/module.api/address.controller.ts
> update PaginationQuery default size to 60

- packages/whale-api-client/__tests__/api/stats.test.ts
- src/module.api/poolpair.service.ts
> Remove DUSD form internal DEX tracking

- packages/whale-api-client/__tests__/api/oracles.test.ts
- packages/whale-api-client/src/api/oracles.ts
- src/module.api/oracle.controller.ts
/kind feature
Get oracle by owner address
Fixes #
> Get oracle by owner address

- src/module.api/address.controller.ts
> revert token-size changes

- src/module.api/poolpair.controller.ts
- src/module.api/poolpair.service.ts
- src/module.api/stats.controller.ts
- src/module.api/subsidy.ts
> fix PoolPair APR calculation for Loan

- src/module.api/stats.controller.ts
> update stats invalidation timing

- src/module.api/_core/api.error.ts
- src/module.api/interceptors/exception.interceptor.ts
> log ApiException more extensively

- .idea/dictionaries/fuxing.xml
- src/e2e.module.ts
- src/main.ts
- src/module.indexer/_module.ts
- src/module.indexer/rpc.block.provider.ts
/kind chore
For graceful shutdown of IndexerModule.
> add shutdown hook for IndexerModule

- packages/whale-api-client/__tests__/api/loan.auction.history.test.ts
- packages/whale-api-client/src/api/loan.ts
- src/e2e.module.ts
- src/module.api/loan.auction.history.e2e.ts
- src/module.api/loan.controller.ts
- src/module.api/loan.vault.service.ts
- src/module.indexer/model/dftx.indexer.ts
- src/module.indexer/model/dftx/_module.ts
- src/module.indexer/model/dftx/place.auction.bid.spec.ts
- src/module.indexer/model/dftx/place.auction.bid.ts
- src/module.model/_module.ts
- src/module.model/vault.auction.batch.history.ts
- src/module.model/vault.auction.history.ts
/kind feature
Fixes part of #541
> Indexing 'placeAuctionBid' + listVaultAuctionHistory API

- packages/whale-api-client/__tests__/api/account.history.test.ts
- packages/whale-api-client/src/api/address.ts
- src/module.api/address.controller.e2e.ts
- src/module.api/address.controller.ts
> add `ListAccountHistory` API

- src/module.api/poolpair.controller.ts
/kind chore
Hide internal PoolPair BURN-DFI
> dex hide BURN-DFI

- packages/whale-api-client/src/api/transactions.ts
> fix(whale-api-client): missing `order: number` for Transaction

- .github/workflows/ci/docker-compose.yml
> bump(docker-compose): update defid to 2.6.0

- .github/workflows/ci/docker-compose.yml
> chore(docker-compose): update fork height for defid

- src/module.database/provider.level/level.database.ts
/kind chore
Previously we run a delete regardless of whether the index has been modified. This makes all operations effectively delete and put operation regardless of the modified contents. This also creates a race condition where the data get deleted before it gets updated. (There is still race condition, but within a reduced scoped from all delete operation to put operation where the index has been modified. E.g. sort position changed.) 
| Data & Index (Model key:data)               | Old Behavior | Old Race Condition                                       | New Behavior | New Race Condition                                                                       |
|---------------------------------------------|--------------|----------------------------------------------------------|------- …
> chore(database): check index is modified before deleting for better performance

- src/module.database/provider.level/level.database.ts
/kind chore
Whale Docker Service Maintenance for better reliability.
> chore(database): revert LevelDatabase options due to memory usage

- src/module.indexer/model/dftx.indexer.ts
- src/module.indexer/model/dftx/_module.ts
- src/module.indexer/model/dftx/create.poolpair.spec.ts
- src/module.indexer/model/dftx/create.poolpair.ts
- src/module.indexer/model/dftx/create.token.spec.ts
- src/module.indexer/model/dftx/create.token.ts
- src/module.indexer/model/dftx/set.loan.token.spec.ts
- src/module.indexer/model/dftx/set.loan.token.ts
- src/module.indexer/model/dftx/update.poolpair.spec.ts
- src/module.indexer/model/dftx/update.poolpair.ts
- src/module.indexer/rpc.block.provider.ts
- src/module.model/_module.ts
- src/module.model/poolpair.token.ts
- src/module.model/poolpair.ts
- src/module.model/token.ts
This reverts commit 9a1b5dc871d9fa8aa05f6592947ce058005e15a5.
/kind feature
> Revert "Drop unused/unexposed database and indexer (#690)"

- .idea/dictionaries/fuxing.xml
- src/module.api/rpc.controller.ts
> feat(rpc): add getburninfo to MethodWhitelist

- src/module.api/rpc.controller.ts
> feat(rpc): add validateaddress to MethodWhitelist

- jest.config.js
- packages/whale-api-client/__tests__/api/stats.test.ts
- packages/whale-api-client/src/api/stats.ts
- src/module.api/_module.ts
- src/module.api/stats.controller.ts
> feat(module-api): add `/stats/supply` API

- src/module.api/stats.controller.ts
/kind fix
Emission burn is not tracked within account layer. This fixes it by explicitly adding emission to be part of `getBurnedTotal()`.
> fix(stats/supply): add missing emission burn that is not tracked within account layer

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- packages/whale-api-client/src/api/poolpairs.ts
- src/module.api/poolpair.controller.ts
- src/module.model/pool.swap.aggregated.ts
> `ApiPagedResponse<PoolSwapAggregated>`

- src/module.indexer/model/dftx/pool.swap.aggregated.ts
> Remove poolswap optimisation

- src/module.indexer/model/dftx/composite.swap.ts
- src/module.indexer/model/dftx/create.pool.pair.ts
> remove comission from swap indexing due to fork in DfTx

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- src/module.indexer/model/dftx/pool.pair.e2e.ts
> Fix poolpair tests

- src/module.api/rpc.controller.ts
/kind feature
Required for the `/stats` endpoint -> https://github.com/DeFiCh/jellyfish/issues/1024
> feat(rpc): add listcommunitybalances to MethodWhitelist

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- packages/whale-api-client/src/api/poolpairs.ts
- src/module.api/poolpair.controller.ts
- src/module.api/poolpair.service.ts
/kind feature
Resolve USD value of AggregatedSwap at current dex prices on controller.
For graphing on https://deploy-preview-1008--defi-scan.netlify.app/dex/5
> feat(api/swaps/aggregated): include USD value for aggregated swaps

- src/module.api/poolpair.controller.ts
> fix(poolpairs-pagination): BURN-DFI will be excluded after ApiPagedResponse have been created

- src/module.api/stats.controller.ts
> chore(cache) cache to improve performance of `/stats/supply`

- src/module.api/stats.controller.ts
> chore(cache): randomize cache duration

- .idea/dictionaries/fuxing.xml
- packages/whale-api-client/__tests__/api/stats.test.ts
- packages/whale-api-client/src/api/stats.ts
- src/module.api/rpc.controller.ts
- src/module.api/stats.controller.ts
> add endpoint /stats/burn to get burn information, disable getburninfo from rpc

- src/module.api/cache/defid.cache.ts
- src/module.api/token.controller.e2e.ts
- src/module.api/token.controller.spec.ts
- src/module.api/token.controller.ts
> feat(module.api): cache get token

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- packages/whale-api-client/src/api/poolpairs.ts
- src/module.api/poolpair.controller.ts
- src/module.api/poolpair.service.ts
/kind feature
Return the swap displaySymbols with the API to allow any UI to extract the right symbol for swap
Fixes #
> Add to listPoolSwapsVerbose to return displaySymbol of swap

- packages/whale-api-client/__tests__/api/poolpairs.swaps.test.ts
- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- packages/whale-api-client/src/api/poolpairs.ts
- src/module.api/poolpair.controller.ts
- src/module.api/poolpair.service.ts
/kind feature
To display buy/sell indicator on Scan individual pool pairs page
Fixes #
> feat(controller/poolswap): Added buy/sell indicator for each swap entry

- src/module.api/poolpair.prices.service.ts
> fix(poolpair.prices): BURN token is not available

- src/module.api/poolswap.pathfinding.service.ts
> fix(poolpair.prices): add ignore burn symbol to computation path

- packages/whale-api-client/__tests__/api/poolpairs.test.ts
- src/module.api/poolpair.controller.e2e.ts
- src/module.api/poolswap.pathfinding.service.ts
> fix(poolswap.pathfinding): ignore pool pair that is status:false

- src/module.api/poolswap.pathfinding.service.ts
/kind fix
Implemented hotfix isPoolPairIgnore for production to check `mainnet` and only ignore id: 48 due to startup performance issues. Using getPoolPair during startup (via interval) is too expensive. Temporary fix on mainnet due to production requirements.
> fix(performance): hotfix isPoolPairIgnore for production to check mainnet only

- src/module.api/rpc.controller.ts
> feat(module.api): Whitelist `getFutureSwapBlock` RPC

- .github/labeler.yml
- .github/workflows/ci.yml
- .github/workflows/ci/docker-compose.yml
- .github/workflows/release-publish.yml
- CONTRIBUTING.md
- README.md
- packages/whale-api-client/package.json
- packages/whale-api-wallet/package.json
https://github.com/DeFiCh/jellyfish/issues/1370
> chore(cleanup): cleanup jellyfishsdk/whale post migration

- .github/workflows/defichain-dependencies.yml
Add PAT for workflows to trigger other workflows.
> chore(workflows): add PAT for workflows to trigger workflows

- .idea/dictionaries/fuxing.xml
- src/module.api/rpc.controller.ts
Whitelist `getpendingfutureswaps` RPC for `0.34.x`
> feat(rpc): whitelist getpendingfutureswaps

- packages/whale-api-client/src/api/poolpairs.ts
- src/module.api/poolpair.controller.e2e.ts
- src/module.api/poolpair.controller.ts
> feat(module-api): Expose dex fee on `PoolPairResult`

- README.md
Add deprecated and migration notice.
> docs(consolidation): add migration notice
